-- ایجاد جدول اعلان‌ها
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- ایجاد جدول دفترچه تلفن شخصی و یادداشت‌ها
CREATE TABLE IF NOT EXISTS public.address_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    UNIQUE(owner_id, contact_id)
);

-- اضافه کردن ستون وضعیت بسته شدن به تیکت‌ها (اگر وجود ندارد)
-- جدول tickets قبلاً ستون status دارد.

-- فعال‌سازی RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.address_book ENABLE ROW LEVEL SECURITY;

-- سیاست‌های RLS برای اعلان‌ها
CREATE POLICY "Users can see their own notifications" ON public.notifications
    FOR SELECT USING (auth.uid() = recipient_id);

-- سیاست‌های RLS برای دفترچه تلفن
CREATE POLICY "Users can manage their own address book" ON public.address_book
    FOR ALL USING (auth.uid() = owner_id);
